### ISSUE TITLE
error in client.lua:51

### ISSUE THREAD

**Issue by JoshuaTheBestGuy** [Kiminaze/freecam#2]
Error loading script client.lua in resource cinematiccam: @cinematiccam/client.lua:51: attempt to index a nil value (global 'NativeUI)
stack traceback:
       @cinematiccam/client.lua:51: in main chunk

**Comment by Shocked-Dev** [comment]
Same Issue

**Comment by Kiminaze** [comment]
Make sure to download the NativeUI from the readme.

**Comment by Shocked-Dev** [comment]
> Make sure to download the NativeUI from the readme.

It's in my server and it still doesnt work.

**Comment by Kiminaze** [comment]
I need more information. What happens when you restart NativeUI?

**Comment by Shocked-Dev** [comment]
Restarted it, Error still happens,
